language: cpp
before_script:
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- cd 01_1
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- cd ../
deploy:
  provider: bintray
  file: "./descriptor.json"
  user: amazgarov
  key: 96c46840b6290a5002f80f98f46addadba463bc4
  skip_cleanup: true
