language: cpp
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- cd 01_2
- cmake .
- cmake --build .
- cmake --build . --target test
- cd ../
